### ISSUE TITLE
"Shell is not a LinearRing" on OSX

### ISSUE THREAD

**Issue by ffaristocrat** [conda-forge/shapely-feedstock#34] opened 2017-12-11 23:50 UTC
While trying to resolve [this issue over in conda-forge/geopandas](https://github.com/conda-forge/geopandas-feedstock/issues/31)(shapefile is from that thread), I traced the problem to the  version (1.6.3-py36_0) conda-forge is installing for shapely.

Running this from a clean Anaconda install on OSX El Capitan 10.11.6:
```
conda create --yes --name GEOTEST python=3.6
source activate GEOTEST
conda install --yes -c conda-forge --override-channels geopandas fiona libgdal numpy scipy libgfortran
python -c "import geopandas as gpd; div20m = gpd.read_file('cb_2016_us_division_20m.shp');"
```

results in repeated

```
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
IllegalArgumentException: geometries must not contain null elements
```

Following on from a suggestion about removing geopandas and pip installing it instead, I repeated it with other libraries as I worked through code in the debugger. I discovered that removing shapely, fiona and geopandas from conda and reinstalling them with pip enables the little one liner test to work. Ditto for code using osmnx that sent me down this rabbit hole in the first place.

```
conda create --yes --name GEOTEST python=3.6
source activate GEOTEST
conda install --yes -c conda-forge --override-channels geopandas fiona libgdal numpy scipy libgfortran
conda remove --yes fiona shapely geopandas
pip install fiona shapely geopandas
python -c "import geopandas as gpd; div20m = gpd.read_file('cb_2016_us_division_20m.shp');"
```

The versions being removed from conda:
```
The following packages will be REMOVED:

    fiona:     1.7.10-py36_2 conda-forge
    geopandas: 0.3.0-py36_0  conda-forge
    shapely:   1.6.3-py36_0  conda-forge
```

The versions being installed by pip:
```
Installing collected packages: fiona, shapely, geopandas
Successfully installed fiona-1.7.10.post1 geopandas-0.3.0 shapely-1.6.3
```

Which, uh, seems to be the same? So I'm not sure what's going on here.

**Comment by jorisvandenbossche** [comment] 2017-12-13 09:13
@ffaristocrat To check this is indeed a shapely issue, could you try to read the file with just fiona? (in the environment where it is failing with geopandas). Then that should not involve shapely or geopandas, and we can see if that works.

Something like 

```
import fiona

# Register format drivers with a context manager
with fiona.drivers():
    # Open a file for reading. We'll call this the "source."
    with fiona.open('...') as source:
        meta = source.meta
        geoms = []
        for fear in source:
            geoms.append(feat['geometry'])
```

**Comment by ffaristocrat** [comment] 2017-12-13 22:14
```
conda create --yes --name FIONATEST python=3.6
source activate FIONATEST
conda install --yes -c conda-forge --override-channels geopandas fiona shapely
python -c "import fiona; [f for f in fiona.open('cb_2016_us_division_20m/cb_2016_us_division_20m.shp')];"
```

This works without any problems. Let me know if you need me to try out anything else.

**Comment by jorisvandenbossche** [comment] 2017-12-14 09:08
OK, that indeed confirms it is a shapely issue, as @ocefpaf also said here https://github.com/conda-forge/geopandas-feedstock/issues/31#issuecomment-351370108

**Comment by ocefpaf** [comment] 2017-12-20 21:18
Note that we are seeing some incompatibilities in the latest OS X system and shapely. I cannot reproduce that using the OS X VM available in Travis-CI and I do not own a Mac to research this further.

Using pip works b/c they are static linked, this suggests that latest OS X may have a system wide `geos` installed, not sure. If so, the patch we have to find `conda` geos is not working :unamused: 

TL;DR I have no idea what the issue really is and I do not have the tools to fix it.

**Comment by cyberjoac** [comment] 2018-03-12 15:22
+1, any solution found ? 
Thanks !

**Comment by phobson** [comment] 2018-03-12 16:27
@ocefpaf I'll try to reproduce this on my machine at home tonight (US/Pacific time).

**Comment by ocefpaf** [comment] 2018-03-12 16:27
Thanks @phobson!

**Comment by denadai2** [comment] 2018-04-10 09:08
+1

**Comment by adah1972** [comment] 2018-04-17 08:15
Reinstalling only geopandas via pip (fiona and shapely are still installed by conda) solved the problem for me.

**Comment by Fil** [comment] 2018-05-04 13:00
same issue for me, & nothing seems to work :(

**Comment by j-la-haye** [comment] 2018-06-15 08:31
Any update here for MacOS? I have reinstalled geopandas via pip and  (fiona and shapely are still installed by conda) but still getting 

Shell is not a LinearRing when trying to call define a shapely Polygon.

**Comment by Fil** [comment] 2018-06-15 08:52
I forgot to give a solution that worked for me, maybe it will help:
```
conda create -n isochrones # name your virtual env as you like, I chose 'isochrones' for some reason
source activate isochrones
conda config --add channels conda-forge
conda install -n isochrones geopandas ipython bokeh requests osmnx jsonschema pandas pyproj geojson geopy Shapely numpy
```

**Comment by ocefpaf** [comment] 2018-06-15 10:40
We cannot reproduce this issue and people that [follow our instructions](https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels) are reporting successful installations.

I'm closing this. If you are still experiencing this issue please try to investigate if your OS X has a geos pre-installed and if shapely is picking that one up.

**Closed by ocefpaf** 2018-06-15 10:40 UTC

**Comment by j-la-haye** [comment] 2018-06-23 17:03
Hi, Thanks for the advice. I have applied the conda config instructions listed. I am still having issues unfortunately. Any pointers as to how I can verify/prevent shapely from using the system OSX geos? Does installing a conda-forge version of geos over ride the system installation?

**Comment by ocefpaf** [comment] 2018-06-26 13:15
> Any pointers as to how I can verify/prevent shapely from using the system OSX geos? 

I'm not even sure that is the problem. I don't have a Mac and our Mac-CI (Travis-CI OS X image) does not reproduce the problem.

We would need a Mac users that is more comfortable with `conda` and the issues here to debug this.

**Comment by phobson** [comment] 2018-06-29 06:08
Just did the following on Mac OS 10.13.5:

```
$ conda create --name=gistest --channel=conda-forge python=3.6 geopandas --yes
$ source activate gistest
$ python -c "import geopandas as gpd; div20m = gpd.read_file('cb_2016_us_division_20m.shp'); print(div20m.shape);"
```
And it printed `(9, 8)`

**Comment by adah1972** [comment] 2018-06-29 06:23
I do not think there is a system-wide libgeos. At least I cannot find any libgeos* under /usr/lib and /System/Library.

I solved my problem by reinstalling geopandas from pip. However, I have now tried `pip uninstall geopandas` followed by `conda install geopandas`, everything seems to be OK at the moment. The original issue could be solved by an update, or it could be a conflict with another channel…

**Comment by adah1972** [comment] 2018-06-29 06:31
Btw, I have tried both the default channel and conda-forge. No errors were encountered.

**Comment by ocefpaf** [comment] 2018-06-29 10:39
Thanks @phobson and @adah1972 for testing. Your results matches our CI :tada: 

People still suffering from this issue either have a unique setup or are not really following the channel best practices recommended the docs.

**Comment by kirankumargmrur** [comment] 2021-10-04 10:38
For me uninstalling shapely and reinstalling with no binary option solved the issue for the latest Mac OS. Below are the commands:
```pip uninstall shapely
 pip install shapely --no-binary shapely```

**Comment by ginaliqili** [comment] 2021-10-05 20:41
> For me uninstalling shapely and reinstalling with no binary option solved the issue for the latest Mac OS. Below are the commands:
> 
> ```
>  pip uninstall shapely
>  pip install shapely --no-binary shapely
> ```

This worked for me as well
