### ISSUE TITLE
OSError: Could not find lib geos_c.dll or load any of its variants

### ISSUE THREAD

**Issue by kev1807** [conda-forge/shapely-feedstock#45] opened 2018-12-30 18:41 UTC
Hi there, 
I am using Windows 10, PyCharm and Anaconda, which I downloaded today from the official website... 
I set up an environment and was just looking at how to make a basic map using cartopy and matplotlib

For improved readability, I use pastebin for extensive stuff, such as the rror message!

https://pastebin.com/srDr9sBt

```
my result for `conda list`
https://pastebin.com/MjYSQx7s


```
It seems like the structure of my env is different from the one that is looked for, as it is looking in 
`C:\\Anaconda3\\envs\\Kevins_environment\\Library\\lib\\geos_c.dll`
while searching for geos_c.dll finds it in
`C:\Anaconda3\envs\Kevins_environment\Library\bin`

I tried simply copying, but it won't work!

my result for `conda info`

no matter what I change - I cannot get active environment to show Kevins_environment (which it should, as I set it to be system interpreter) (I am giving you this output from PyCharm)

>    active environment : None
>        user config file : C:\Users\KW\.condarc
>  populated config files : C:\Users\KW\.condarc
>           conda version : 4.5.12
>     conda-build version : 3.17.6
>          python version : 3.7.1.final.0
>        base environment : C:\Anaconda3  (writable)
>            channel URLs : https://conda.anaconda.org/conda-forge/win-64
>                           https://conda.anaconda.org/conda-forge/noarch
>                           https://repo.anaconda.com/pkgs/main/win-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/free/win-64
>                           https://repo.anaconda.com/pkgs/free/noarch
>                           https://repo.anaconda.com/pkgs/r/win-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>                           https://repo.anaconda.com/pkgs/pro/win-64
>                           https://repo.anaconda.com/pkgs/pro/noarch
>                           https://repo.anaconda.com/pkgs/msys2/win-64
>                           https://repo.anaconda.com/pkgs/msys2/noarch
>           package cache : C:\Anaconda3\pkgs
>                           C:\Users\KW\AppData\Local\conda\conda\pkgs
>        envs directories : C:\Anaconda3\envs
>                           C:\Users\KW\AppData\Local\conda\conda\envs
>                           C:\Users\KW\.conda\envs
>                platform : win-64
>              user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
>           administrator : False
>              netrc file : None
>            offline mode : False
> 

when I use it via cmd it actually works fine. 
this might be a configuration issue which I cannot wrap my head around?! 
Can anyone help with this please? 

Edit: 
I just checked: When I use Spyder it works fine ...

**Comment by phobson** [comment] 2019-01-07 16:08
From the command line and spyder, it works. Where does it not work?

**Comment by phobson** [comment] 2019-01-07 16:09
Also, according to the output of `conda list`, you don't have any libraries from conda-forge. Was that intentional? If so, the issue is with the packages from the default channel (someone else) and not conda-forge (this repo)

**Comment by ocefpaf** [comment] 2019-01-07 16:18
Closing this b/c it looks like an env confusion and not a problem with the package.

**Closed by ocefpaf** 2019-01-07 16:18 UTC
