### ISSUE TITLE
Conda install of shapely fails on Mac OSx

### ISSUE THREAD

**Issue by pradal** [conda-forge/shapely-feedstock#64] opened 2020-04-02 07:08 UTC
Issue:

After installing shapely, I have an error when I run:

`from shapely import geos`

The error is:

```Traceback (most recent call last): 
    File "<stdin>", line 1, in <module> 
    File "/Users/pradal/miniconda3/envs/shapeely/lib/python3.8/site-packages/shapely/geos.py", line 113, in <module> 
        free = load_dll('c').free 
    File "/Users/pradal/miniconda3/envs/shapeely/lib/python3.8/site-packages/shapely/geos.py", line 54, in load_dll 
        raise OSError( 
OSError: Could not find lib c or load any of its variants [].
```

**conda install libcxx but not libc** 
Everything works if I change (in geos.py, line 113)

`free = load_dll('c').free`

by

`free = load_dll('cxx').free`

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2020.1.1                      0
certifi                   2019.11.28               py38_1
geos                      3.7.1                h0a44026_0
intel-openmp              2019.4                      233
libcxx                    4.0.1                hcfea43d_1
libcxxabi                 4.0.1                hcfea43d_1
libedit                   3.1.20181209         hb402a30_0
libffi                    3.2.1                h475c297_4
libgfortran               3.0.1                h93005f0_2
mkl                       2019.4                      233
mkl-service               2.3.0            py38hfbe908c_0
mkl_fft                   1.0.15           py38h5e564d8_0
mkl_random                1.1.0            py38h6440ff4_0
ncurses                   6.2                  h0a44026_0
numpy                     1.18.1           py38h7241aed_0
numpy-base                1.18.1           py38h6575580_1
openssl                   1.1.1f               h1de35cc_0
pip                       20.0.2                   py38_1
python                    3.8.2                hc70fcce_0
readline                  8.0                  h1de35cc_0
setuptools                46.1.3                   py38_0
shapely                   1.6.4            py38he8793f5_0
six                       1.14.0                   py38_0
sqlite                    3.31.1               ha441bb4_0
tk                        8.6.8                ha441bb4_0
wheel                     0.34.2                   py38_0
xz                        5.2.4                h1de35cc_4
zlib                      1.2.11               h1de35cc_3

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
    active environment : shapely
    active env location : /Users/pradal/miniconda3/envs/shapely
            shell level : 2
       user config file : /Users/pradal/.condarc
 populated config files :
          conda version : 4.8.1
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __osx=10.15.1
       base environment : /Users/pradal/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/pradal/miniconda3/pkgs
                          /Users/pradal/.conda/pkgs
       envs directories : /Users/pradal/miniconda3/envs
                          /Users/pradal/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.1 requests/2.22.0 CPython/3.7.4 Darwin/19.0.0 OSX/10.15.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by pradal** [comment] 2020-04-02 07:27
This issue is similar to #53, #52 , ...
The fix is only depending on libc rather than libc++.
I have no homebrew or macport on my computer, neither geos

**Comment by xylar** [comment] 2020-04-02 08:11
@pradal, your `conda list` isn't showing `conda-forge` as the channel for your packages, and this likely means they're not coming from `conda-forge`.  `conda-forge` is also not listed among your channels in your `conda info`.  Could you describe how you created your environment?

Here's what I did, starting from Miniconda3:
```
conda config --add channels conda-forge
conda config --set channel_priority strict
conda create -y -n test python=3.8 shapely geos
conda activate test
python -c "from shapely import geos"
```
I don't see any errors.

I suspect this problem relates to the version of `shapely` on the `defaults` channel, not on `conda-forge`.  If you agree, could you please close this issue and open an issue over there instead (https://github.com/conda/conda/issues)?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/user162691/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28       py38h32f6830_1    conda-forge
geos                      3.8.1                h4a8c4bd_0    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libcxx                    9.0.1                         1    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgfortran               4.0.0                         2    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libopenblas               0.3.9                h3d69b6c_0    conda-forge
llvm-openmp               9.0.1                h28b9765_2    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.18.1           py38h1f821a2_1    conda-forge
openssl                   1.1.1f               h0b31af3_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
python                    3.8.2           hd5f0129_5_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
setuptools                46.1.3           py38h32f6830_0    conda-forge
shapely                   1.7.0            py38h5b1fbde_2    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.4             h0b31af3_1002    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : test
    active env location : /Users/user162691/miniconda3/envs/test
            shell level : 2
       user config file : /Users/user162691/.condarc
 populated config files : /Users/user162691/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.1
         python version : 3.7.3.final.0
       virtual packages : __osx=10.15.3
       base environment : /Users/user162691/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/user162691/miniconda3/pkgs
                          /Users/user162691/.conda/pkgs
       envs directories : /Users/user162691/miniconda3/envs
                          /Users/user162691/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.3 Darwin/19.3.0 OSX/10.15.3
                UID:GID : 508:204
             netrc file : None
           offline mode : False
```
</details>

**Comment by pradal** [comment] 2020-04-02 08:16
I tested both wih defaults and conda-forge. 
However, I change the conda-forge package so that why I do not report.
In fact I have the same error with both pip, conda default and conda-forge.
On Python 3.8, libc is not installed, only libcxx.

**Comment by xylar** [comment] 2020-04-02 09:05
Okay, thank you for re-testing on conda-forge.  It must be that others tests (including mine) are picking up libc from elsewhere?

**Comment by xylar** [comment] 2020-04-02 09:12
Could it be that this is an issue with `shapely` and should be reported here?
https://github.com/Toblerity/Shapely/issues

If none of the dependencies bring in `libc` and `shapely` itself doesn't depend on `libc` (but rather seems to be assuming that `geos` does), isn't the problem with `shapely` itself, not the feedstock?

**Comment by xylar** [comment] 2020-04-02 09:31
Alternatively, the problem could be that `geos` isn't including `libc` as a dependency.  @ocefpaf, could you weight in on this?

**Comment by xylar** [comment] 2020-04-02 09:39
So if I just install `geos`, I see:
```
$ conda list
# packages in environment at /home/xylar/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
geos                      3.8.1                he1b5a44_0    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
```
So no `libcxx` or `libc` but rather `libstdcxx-ng` and `libgcc-ng`.  I have to admit that I don't know a ton about how dynamic libraries are handled in general, and in python in particular.  But it seems like `shapely` is expecting a particular name library name `libc` that isn't what `goes` is using.

**Comment by xylar** [comment] 2020-04-02 10:12
A added a test for importing `shapely.geos` in #65 and it passes.  I'll keep looking into this but I haven't been able to reproduce it anywhere.

**Comment by ocefpaf** [comment] 2020-04-02 13:01
Do you by any chance have another installation of geos? Maybe from homebrew? In the past users had issues with that.

Also, as far as I recall I know `libc` should come from your system, is that right @isuruf?

**Comment by pradal** [comment] 2020-04-02 13:24
No other installation. Neither Homebrew nor MacPort.
As I solve the problem by replacing libc to libcxx, I can provide a patch to shapely.

**Comment by pradal** [comment] 2020-04-02 13:30
Moreover, it seems that : 

> The libc library is already loaded by Python, and posix exposes all the
> functions from a global namespace. AFAIK.

So just doing
`CDLL(None).free`
works as expected.

**Comment by isuruf** [comment] 2020-04-02 14:26
`libc` equivalent of macOS is `libSystem`, so `load_dll('c')` doesn't work.
This is an issue upstream and not a packaging issue.

**Comment by xylar** [comment] 2020-04-02 14:34
@pradal, can you post this issue on https://github.com/Toblerity/Shapely/issues instead?  I'm going to close it here.

**Closed by xylar** 2020-04-02 14:34 UTC

**Comment by pradal** [comment] 2020-04-02 14:36
Sure. Thank you.
