### ISSUE TITLE
conda shapely install produces errors. 

### ISSUE THREAD

**Issue by ltgthunder** [conda-forge/shapely-feedstock#35] opened 2017-12-20 20:51 UTC
Installed:
shapely                   1.6.3                    py35_0    conda-forge
&
geos                      3.6.2                         1    conda-forge

BUT when I run:
from shapely.geometry import Point

I get: 

//anaconda/lib/python3.5/site-packages/shapely/geos.py in <module>()
    174 
    175 # Apply prototypes for the libgeos_c functions
--> 176 prototype(_lgeos, geos_version)
    177 
    178 # If we have the new interface, automatically detect all function

//anaconda/lib/python3.5/site-packages/shapely/ctypes_declarations.py in prototype(lgeos, geos_version)
     29     if not geos_version >= (3, 3, 0):
     30         raise UnsupportedGEOSVersionError(
---> 31             "Shapely requires GEOS version 3.3.0 or newer.")
     32 
     33     # Initialization, cleanup, version.

UnsupportedGEOSVersionError: Shapely requires GEOS version 3.3.0 or newer.

I clearly have GEOS version 3.6.2
also now have geos_c library files in my anaconda $PATH as well as /usr/local/lib  (this was my initial error in building / using shapely).

On mac OSX Sierra using jupyter notebook.

I have been across the web trying to find answers, but hours later no luck.  Would appreciate any guidance..

**Comment by ocefpaf** [comment] 2017-12-20 21:18
Closing this as duplicate of https://github.com/conda-forge/shapely-feedstock/issues/34#issuecomment-353184949

**Closed by ocefpaf** 2017-12-20 21:18 UTC

**Comment by ltgthunder** [comment] 2017-12-20 21:50
note: this was because libgeos_c  was also in /usr/local/lib  even when modifying $LD_LIBRARY_PATH to search /anaconda/bin first

moved files out of /usr/local/lib (hopefully I remember this in the future) and was able to use shapely.geometry

**Comment by ocefpaf** [comment] 2017-12-20 22:30
@ltgthunder still, this version should look for geos in the conda path first. Something is amiss :unamused:
