### ISSUE TITLE
lgeos import error

### ISSUE THREAD

**Issue by snowman2** [conda-forge/shapely-feedstock#17] opened 2017-03-15 18:38 UTC
On Mac with Python 3.5:
```
$ conda config --add channels conda-forge
$ conda install --yes gdal numpy six requests geopandas pillow celery psycopg2 geoalchemy2
$ python -c "from shapely.geos import lgeos"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rdchlads/anaconda3/envs/gaia/lib/python3.5/site-packages/shapely/geos.py", line 72, in <module>
    free = load_dll('c').free
  File "/Users/rdchlads/anaconda3/envs/gaia/lib/python3.5/site-packages/shapely/geos.py", line 61, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib c or load any of its variants [].
```

**Comment by ocefpaf** [comment] 2017-03-17 18:44
I put https://github.com/conda-forge/shapely-feedstock/pull/18 together to check this on Travis-CI because I don't own a Mac. But I could not reproduce it in my fork. Can you provide more details of the problem?

**Comment by ocefpaf** [comment] 2017-03-18 21:36
@snowman2 I cannot reproduce that in #18 I guess that this is specific to your setup. I am closing this but we can re-open if you can provide more details on how to reproduce the problem.

**Closed by ocefpaf** 2017-03-18 21:36 UTC
